[[redirects]]
  from = "/*"
  to = "https://lizard-arrow-pastry.glitch.me/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200